spring:
  application:
    name: migration-study

  datasource:
    url: jdbc:h2:mem:szs;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 1234

  ### URL: http://localhost:8080/h2-console ###
  h2:
    console:
      path: /h2-console
      enabled: true